### ISSUE TITLE
论left-pad函数的实现

### ISSUE THREAD

**Issue by shengxinjing** [shengxinjing/fe-advanced-interview#10]
# 论left-pad的实现

这两天微博上看到左耳朵耗子吐槽了一下node社区的left-pad的代码，[原po链接](http://weibo.com/1401880315/DnzvP5fwr?type=comment#_rnd1458794509276)

![01](https://cloud.githubusercontent.com/assets/1905176/14008527/a7453084-f1bc-11e5-83f4-8926718ca3f4.png)

我也思考了一下 怎么用实现一个left-pad比较合适,上图代码确实比较搓
leftpad功能，就是字符串前面拼指定字符到固定长度，比如
leftpad('hello',20,'1')，就要返回'111111111111111hello'
## 版本1 用数组+join

```

function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length;
    return Array(len).join(ch) + str;
}

```
## 版本2 用一个带length属性的对象去实现join，免去了创建arr的步骤，性能应该回好点

```

function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length;
    return Array.prototype.join.call({
        length:len
    },ch)+str;
}

```

如果把Array.prototype.join缓存到外部变量里，多次使用速度更快

```
var _join = Array.prototype.join
function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length;
    return _join.call({
        length:len
    },ch)+str;
}


```
### 版本3 二分法

上面复杂度都是O(N)的，既然核心思路是把字符串重复n次，可以用二分法，比如把s，重复20次，拼在str前面，大概过程如下

```
total = ''
ch = 's'
20是偶数
    ch变成ss
    长度变成10
        10是偶数
            ch变成ssss
            长度变成5
                5是奇数
                    total += ch(total变成ssss)
                    ch变成ssssssss(8个)
                    长度变成2
                        2是偶数
                            ch继续变成(ssssssssssssssss)(16个s)
                            长度变成1
                                total= total+ch（4个加16个）
                                结束代码 拼接str 返回

```

代码如下

```
function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length,
        total = ''
    while (true) {
        // 如果len是基数，total上就加一个ch
        if (len % 2 == 1) total += ch;
        if (len == 1) return total + str;;
        // 每次ch都变成chch
        ch += ch;
        //长度减半
        len = parseInt(len / 2);
    }

}

```

最后写完这些，看了耗子大神微博贴的代码，突然想起求余和除以二取整，可以用 按位与len&1 和右移len>>1代替，囧，还是代码写的太少，没想到
## 最后代码

```

function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length,
        total = ''
    while (true) {
        // 如果len是基数，total上就加一个ch
        if (len & 1 == 1) total += ch;
        if (len == 1) return total + str;;
        // 每次ch都变成chch
        ch += ch;
        //长度减半
        len = len>>1;

    }

}


```

最后再优化一下循环

```

function leftpad(str, len, ch) {
    if (!ch && ch !== 0) ch = ' ';
    var len = len - str.length,
        total = ''
    while (len) {
        // 如果len是基数，total上就加一个ch
        (len & 1) && (total += ch)
        // 每次ch都变成chch
        ch += ch;
        //长度减半
        len = len >> 1;

    }
    return total + str

}


```

大家可以尝试用python实现一下（不要用自带的rjust），本文仅提供一个思路，很小的一个功能函数，可能还会有很多更好的优化和实现，欢迎大家多指教写代码过程中还是要多思考，共勉
喜欢请star

**Comment by AbnerZheng** [comment]
二分法的分析是有问题的，如果不是拼接而仅仅如快速幂一样只使用加法和乘法等常数时间操作的运算，这样是可以到 Theta(log n)，但是因为这里是字符串拼接，如果用vector（js里面的array）来存储，那么前拼接就要O(n)，这样算起来，你所说的二分法还是Theta(n).

**Comment by lwhhhh** [comment]
@AbnerZheng 他里面的二分法代码并没有使用array来存储字符串

**Comment by shengxinjing** [comment]
@AbnerZheng 求指教，我代码里 应该没用array存储数据 求更好性能的代码

**Comment by AbnerZheng** [comment]
@shengxinjing @lwhhhh 是我想当然了，js引擎下的字符串还不是数组存储的，套了C++的了，测试了一下还是Theta(log n )

**Comment by AbnerZheng** [comment]
@shengxinjing @lwhhhh 微博用户“哦胖茶”的微博给了js引擎的源码地址，实现方式是 rope (tree)算法，能够做到常数级拼接。

**Comment by lwhhhh** [comment]
@shengxinjing thx~

**Comment by shengxinjing** [comment]
@AbnerZheng 非常感谢，这个好牛逼，还真没看过js引擎的源码，Thanks

**Comment by DOTA2mm** [comment]
实际上通过join一个空数组得到的字符串长度是比数组长度少1位的，所以这样方法得到的字符串比传入的长度少一位

**Comment by Agcaiyun** [comment]
是的，同意楼上的说法，join 方法得到的字符串确实比 len 少 1
![image](https://user-images.githubusercontent.com/26242748/29669767-1837612a-8917-11e7-8123-a2d7aef11693.png)

**Comment by KsRyY** [comment]
JS的位移不是很烂吗？我记得JS的所有数字都是浮点数，而JS的位移操作是按java的实现的，要把数字转换成整数才能位移啊？

**Comment by zhangzs000** [comment]
位运算的性能不一定高
